backend:
  name: git-gateway
  repo: jolane/sallys-kitchen-netlify-cms
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: sections
    label: "Sections"
    files:
      - file: "src/data/Intro.md"
        label: "Intro"
        name: "intro"
        fields:
          - {label: "Words (comma seperated)", name: "is_words", widget: "string"}
      - file: "src/data/About.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Paragraph", name: "paragraph", widget: "text"}
          - {label: "Large Text", name: "large_text", widget: "text"}
          - {label: "Paragraph 2", name: "paragraph2", widget: "text"}
      - file: "src/data/TheKitchen.md"
        label: "The Kitchen"
        name: "thekitchen"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Paragraph", name: "paragraph", widget: "text"}
      - file: "src/data/Images.md"
        label: "Images"
        name: "images"
        fields:
          - {label: "Image One", name: "image_one", widget: "image"}
          - {label: "Image Two", name: "image_two", widget: "image"}
          - {label: "Image Three", name: "image_three", widget: "image"}
          - {label: "Image Four", name: "image_four", widget: "image"}
      - file: "src/data/Where.md"
        label: "Where"
        name: "where"
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Large Text", name: "large_text", widget: "text"}
          - {label: "Paragraph", name: "paragraph", widget: "text"}



