backend:
  name: git-gateway
  repo: jolane/sallys-kitchen-netlify-cms
  branch: master

media_folder: "static/images"
public_folder: "/images"

collections:
  - name: sections
    label: "Sections"
    files:
      - file: "src/data/Intro.md"
        label: "Intro"
        name: "intro"
        fields:
          - {label: "Words (comma seperated)", name: "is_words", widget: "string"}
      - file: "src/data/Landing.md"
        label: "Content"
        name: "content"
        fields:
          - {label: "About Title", name: "about_title", widget: "string"}
          - {label: "About Paragraph", name: "about_paragraph", widget: "text"}
          - {label: "About Large Text", name: "about_large_text", widget: "text"}
          - {label: "About Paragraph 2", name: "about_paragraph2", widget: "text"}

          - {label: "Image One", name: "image_one", widget: "image"}
          - {label: "Image Two", name: "image_two", widget: "image"}
          - {label: "Image Three", name: "image_three", widget: "image"}
          - {label: "Image Four", name: "image_four", widget: "image"}

          - {label: "The Kitchen Title", name: "kitchen_title", widget: "string"}
          - {label: "The Kitchen Text", name: "kitchen_text", widget: "text"}

          - {label: "Breakfast Menu", name: "breakfast_menu", widget: "file"}

          - {label: "What's Cooking Title", name: "cooking_title", widget: "string"}
          - {label: "What's Cooking Text", name: "cooking_text", widget: "text"}

          - {label: "Functions Title", name: "functions_title", widget: "string"}
          - {label: "Functions Text", name: "functions_text", widget: "text"}
          - {label: "Functions Large Text", name: "functions_large_text", widget: "text"}

          - {label: "Where Title", name: "where_title", widget: "string"}
          - {label: "Where Large Text", name: "where_large_text", widget: "text"}
          - {label: "Where Text", name: "where_text", widget: "text"}

          - {label: "Hours Heading", name: "hours_title", widget: "string"}
          - {label: "Hours Text", name: "hours_text", widget: "text"}